import boto3
import time

# --- INPUT REQUIRED ---
# These have been redacted for security purposes. 
# In a live environment, these would be the IDs generated by the builder script.
SUBNET_ID = 'subnet-xxxxxxxxxxxxxxxxx' 
SECURITY_GROUP_ID = 'sg-xxxxxxxxxxxxxxxxx'
# ----------------------

ec2 = boto3.resource('ec2', region_name='us-east-1')

print("Target locked. Fetching the latest free-tier Amazon Linux OS...")

# Deploy the EC2 Instance
instance = ec2.create_instances(
    ImageId='ami-0c101f26f147fa7fd', # Standard Amazon Linux 2023 AMI
    MinCount=1,
    MaxCount=1,
    InstanceType='t2.micro',
    SubnetId=SUBNET_ID,
    SecurityGroupIds=[SECURITY_GROUP_ID],
    TagSpecifications=[{
        'ResourceType': 'instance',
        'Tags': [{'Key': 'Name', 'Value': 'SOC-Target-Machine'}]
    }]
)[0]

print(f"Deploying Target Server into Subnet: {SUBNET_ID}...")
print("Server is booting up. Waiting for it to come online...")

instance.wait_until_running()
instance.reload()

print("\nMISSION ACCOMPLISHED: Target Deployed.")
print(f"[!] TARGET PUBLIC IP ADDRESS: {instance.public_ip_address}")
